services:
  - type: web
    name: nba-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
    plan: free
    envVars:
      - key: SPORTSDATA_API_KEY
        sync: 861c2d372b8a409b9db663cb0bc08dbc
      - key: OPENAI_API_KEY
        sync: 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
      - key: TELEGRAM_BOT_TOKEN
        sync: 7972586424:AAH7YaQ2c2K8GhD_FThpYku3VjmcX_mZkJI
